<a href="https://colab.research.google.com/github/arunravi8595/CE706/blob/main/CE706_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#import required libraries to work with data
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [5]:
#Load and Read data
meta_df = pd.read_csv('https://raw.githubusercontent.com/arunravi8595/CE706/main/metadata%20-%20NEW.csv')
meta_df.shape #Number of rows and columns in the dataset

(1000, 19)

In [10]:
#File Sample
meta_df.head()

cord_uid  ... s2_id
0  ug7v899j  ...   NaN
1  02tnwd4m  ...   NaN
2  ejv2xln0  ...   NaN
3  2b73a28n  ...   NaN
4  9785vg6d  ...   NaN

[5 rows x 19 columns]

In [6]:
#Check empty slots in data
meta_df.isnull().sum()

cord_uid               0
sha                   36
source_x               0
title                  0
doi                    0
pmcid                  0
pubmed_id              0
license                0
abstract              44
publish_time           0
authors               14
journal                0
mag_id              1000
who_covidence_id    1000
arxiv_id            1000
pdf_json_files        36
pmc_json_files        37
url                    0
s2_id               1000
dtype: int64

# **Tokenization**

In [7]:
#Get word index using tokenizer
Tokenizer = Tokenizer(num_words=100)
Tokenizer.fit_on_texts(meta_df)
word_index = Tokenizer.word_index
print(word_index)

{'id': 1, 'json': 2, 'files': 3, 'cord': 4, 'uid': 5, 'sha': 6, 'source': 7, 'x': 8, 'title': 9, 'doi': 10, 'pmcid': 11, 'pubmed': 12, 'license': 13, 'abstract': 14, 'publish': 15, 'time': 16, 'authors': 17, 'journal': 18, 'mag': 19, 'who': 20, 'covidence': 21, 'arxiv': 22, 'pdf': 23, 'pmc': 24, 'url': 25, 's2': 26}


In [ ]:
#Create sequences from tokens created for the words
sequences = Tokenizer.texts_to_sequences(meta_df)
print(sequences)

[[4, 5], [6], [7, 8], [9], [10], [11], [12, 1], [13], [14], [15, 16], [17], [18], [19, 1], [20, 21, 1], [22, 1], [23, 2, 3], [24, 2, 3], [25], [26, 1]]


In [ ]:
#sequencing/padding sentences with different lengths (to arrange in a ordered manner)
padded = pad_sequences(sequences)
print(padded)

[[ 0  4  5]
 [ 0  0  6]
 [ 0  7  8]
 [ 0  0  9]
 [ 0  0 10]
 [ 0  0 11]
 [ 0 12  1]
 [ 0  0 13]
 [ 0  0 14]
 [ 0 15 16]
 [ 0  0 17]
 [ 0  0 18]
 [ 0 19  1]
 [20 21  1]
 [ 0 22  1]
 [23  2  3]
 [24  2  3]
 [ 0  0 25]
 [ 0 26  1]]


# **Sentence splitting**

In [9]:
#Sentence splitting in the contents of Abstract column
meta_df["abstract"].str.split(",")

0      [OBJECTIVE: This retrospective chart review de...
1      [Inflammatory diseases of the respiratory trac...
2      [Surfactant protein-D (SP-D) participates in t...
3      [Endothelin-1 (ET-1) is a 21 amino acid peptid...
4      [Respiratory syncytial virus (RSV) and pneumon...
                             ...                        
995    [BACKGROUND: Mannose-binding lectin is a colle...
996    [It has been nearly a century since the early ...
997    [BACKGROUND: Salmonellosis in water buffalo (B...
998    [BACKGROUND: Cerebral malaria (CM) and severe ...
999    [Motivation: Laboratory RNA structure determin...
Name: abstract, Length: 1000, dtype: object

In [14]:
# Find keyword in specific column ( Search for "malaria" in abstract)
meta_df["abstract"].str.contains("malaria")

0      False
1      False
2      False
3      False
4      False
       ...  
995    False
996    False
997    False
998     True
999    False
Name: abstract, Length: 1000, dtype: object